/*
 * UserRegister.java
 *
 * Created on __DATE__, __TIME__
 */

package View;

import java.awt.Font;
import java.awt.Image;
import java.awt.Toolkit;
import java.sql.SQLException;

import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;

import Control.Ad;
import Control.AdTableModel;
import Control.Admin;
import Control.FontControl;
import Control.ModelFactory;
import Control.User;

/**
 * 
 * @author __USER__
 */
public class AddAd extends javax.swing.JFrame {
	AdTableModel atm;
	Object[][]datas =null;
	JScrollPane jsl;
	private static final long serialVersionUID = 1L;

	/** Creates new form UserRegister */
	public AddAd() {
		initComponents();
		Image icon = Toolkit.getDefaultToolkit().getImage("imgs//icon.jpg");
		this.setTitle("广告添加");
		this.setVisible(true);
		this.setResizable(false);
		this.setLocationRelativeTo(null);
		this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
		this.setIconImage(icon);

	}
	
	public AddAd(AdTableModel atm,Object [][]datas,JScrollPane jsl){
		this.atm = atm;
		this.datas = datas;
		this.jsl = jsl;
		initComponents();
		Image icon = Toolkit.getDefaultToolkit().getImage("imgs//icon.jpg");
		this.setTitle("广告添加");
		this.setVisible(true);
		this.setResizable(false);
		this.setLocationRelativeTo(null);
		this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
		this.setIconImage(icon);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {
		

		jPanel2 = new javax.swing.JPanel();
		jLabel5 = new javax.swing.JLabel();
		jLabel6 = new javax.swing.JLabel();
		jLabel7 = new javax.swing.JLabel();
		phoneTxt = new javax.swing.JTextField();
		UpdateBtn = new javax.swing.JButton();
		emailTxt = new javax.swing.JTextField();
		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		jLabel3 = new javax.swing.JLabel();
		unameTxt = new javax.swing.JTextField();
		companyTxt = new javax.swing.JTextField();
		jLabel4 = new javax.swing.JLabel();
		adTxt = new javax.swing.JTextField();
		jLabel8 = new javax.swing.JLabel();
		adUrlTxt = new javax.swing.JTextField();
		jButton1 = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource(
				"/imgs/user-icon.png"))); // NOI18N

		jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource(
				"/imgs/company.png"))); // NOI18N

		jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource(
				"/imgs/tel-icon.png"))); // NOI18N

		phoneTxt.setForeground(new java.awt.Color(153, 153, 153));
		phoneTxt
				.setText("\u8bf7\u8f93\u5165\u60a8\u7684\u7535\u8bdd\u53f7\u7801");
		phoneTxt.addFocusListener(new java.awt.event.FocusAdapter() {
			public void focusGained(java.awt.event.FocusEvent evt) {
				if(phoneTxt.getText().equals("\u8bf7\u8f93\u5165\u60a8\u7684\u7535\u8bdd\u53f7\u7801")){
					phoneTxt.setText("");
				}
			}
			public void focusLost(java.awt.event.FocusEvent evt) {
				if(phoneTxt.getText().equals("")){
					phoneTxt.setText("\u8bf7\u8f93\u5165\u60a8\u7684\u7535\u8bdd\u53f7\u7801");
				}
			}
		});
		UpdateBtn.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 24));
		UpdateBtn.setText("\u786e\u8ba4\u6dfb\u52a0");
		UpdateBtn.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				UpdateBtnActionPerformed(evt);
			}
		});

		emailTxt.setForeground(new java.awt.Color(153, 153, 153));
		emailTxt
				.setText("\u8bf7\u8f93\u5165\u60a8\u7684\u90ae\u7bb1\u5730\u5740");
		emailTxt.addFocusListener(new java.awt.event.FocusAdapter() {
			public void focusGained(java.awt.event.FocusEvent evt) {
				if(emailTxt.getText().equals("\u8bf7\u8f93\u5165\u60a8\u7684\u90ae\u7bb1\u5730\u5740")){
					emailTxt.setText("");
				}
			}
			public void focusLost(java.awt.event.FocusEvent evt) {
				if(emailTxt.getText().equals("")){
					emailTxt.setText("\u8bf7\u8f93\u5165\u60a8\u7684\u90ae\u7bb1\u5730\u5740");
				}
			}
		});
		jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource(
				"/imgs/mail-icon.png"))); // NOI18N

		jLabel2.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18));
		jLabel2
				.setText("\u73b0\u5728\u53ef\u4ee5\u6dfb\u52a0\u5e7f\u544a\u4fe1\u606f");

		jLabel3.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18));
		jLabel3.setText("\u6b22\u8fce\u4f7f\u7528SkyDisk");

		unameTxt.setForeground(new java.awt.Color(153, 153, 153));
		unameTxt.setText("\u8f93\u5165\u4f60\u7684\u7528\u6237\u540d");
		unameTxt.addFocusListener(new java.awt.event.FocusAdapter() {
			public void focusGained(java.awt.event.FocusEvent evt) {
				if(unameTxt.getText().equals("\u8f93\u5165\u4f60\u7684\u7528\u6237\u540d")){
					unameTxt.setText("");
				}
			}
			public void focusLost(java.awt.event.FocusEvent evt) {
				if(unameTxt.getText().equals("")){
					unameTxt.setText("\u8f93\u5165\u4f60\u7684\u7528\u6237\u540d");
				}
			}
		});
		companyTxt.setForeground(new java.awt.Color(153, 153, 153));
		companyTxt.setText("\u8f93\u5165\u4f60\u7684\u7528\u6237\u540d");
		companyTxt.addFocusListener(new java.awt.event.FocusAdapter() {
			public void focusGained(java.awt.event.FocusEvent evt) {
				if(companyTxt.getText().equals("\u8f93\u5165\u4f60\u7684\u7528\u6237\u540d")){
					companyTxt.setText("");
				}
			}
			public void focusLost(java.awt.event.FocusEvent evt) {
				if(companyTxt.getText().equals("")){
					companyTxt.setText("\u8f93\u5165\u4f60\u7684\u7528\u6237\u540d");
				}
			}
		});
		jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource(
				"/imgs/ad-icon.png"))); // NOI18N

		adTxt.setText("\u8bf7\u8f93\u5165\u5e7f\u544a\u540d\u79f0");
		adTxt.setForeground(new java.awt.Color(153, 153, 153));
		adTxt.addFocusListener(new java.awt.event.FocusAdapter() {
			public void focusGained(java.awt.event.FocusEvent evt) {
				if(adTxt.getText().equals("\u8bf7\u8f93\u5165\u5e7f\u544a\u540d\u79f0")){
					adTxt.setText("");
				}
			}
			public void focusLost(java.awt.event.FocusEvent evt) {
				if(adTxt.getText().equals("")){
					adTxt.setText("\u8bf7\u8f93\u5165\u5e7f\u544a\u540d\u79f0");
				}
			}
		});
		jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource(
				"/imgs/url-icon.png"))); // NOI18N

		adUrlTxt.setText("\u8bf7\u8f93\u5165\u5e7f\u544a\u5730\u5740");
		adUrlTxt.setForeground(new java.awt.Color(153, 153, 153));
		adUrlTxt.addFocusListener(new java.awt.event.FocusAdapter() {
			public void focusGained(java.awt.event.FocusEvent evt) {
				if(adUrlTxt.getText().equals("\u8bf7\u8f93\u5165\u5e7f\u544a\u5730\u5740")){
					adUrlTxt.setText("");
				}
			}
			public void focusLost(java.awt.event.FocusEvent evt) {
				if(adUrlTxt.getText().equals("")){
					adUrlTxt.setText("\u8bf7\u8f93\u5165\u5e7f\u544a\u5730\u5740");
				}
			}
		});
		jButton1.setText("选择");
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});
		javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(
				jPanel2);
		jPanel2.setLayout(jPanel2Layout);
		jPanel2Layout
				.setHorizontalGroup(jPanel2Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								javax.swing.GroupLayout.Alignment.TRAILING,
								jPanel2Layout
										.createSequentialGroup()
										.addGap(66, 66, 66)
										.addGroup(
												jPanel2Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																jPanel2Layout
																		.createSequentialGroup()
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addComponent(
																				jLabel7)
																		.addGap(
																				18,
																				18,
																				18)
																		.addComponent(
																				phoneTxt,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				201,
																				Short.MAX_VALUE))
														.addGroup(
																jPanel2Layout
																		.createSequentialGroup()
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addComponent(
																				jLabel6)
																		.addGap(
																				18,
																				18,
																				18)
																		.addComponent(
																				companyTxt,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				201,
																				Short.MAX_VALUE))
														.addComponent(
																jLabel3,
																javax.swing.GroupLayout.Alignment.TRAILING,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																191,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addGroup(
																jPanel2Layout
																		.createSequentialGroup()
																		.addComponent(
																				jLabel5)
																		.addGap(
																				18,
																				18,
																				18)
																		.addComponent(
																				unameTxt,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				201,
																				Short.MAX_VALUE))
														.addComponent(
																jLabel2,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																204,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addGroup(
																jPanel2Layout
																		.createSequentialGroup()
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addGroup(
																				jPanel2Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING)
																						.addGroup(
																								jPanel2Layout
																										.createSequentialGroup()
																										.addComponent(
																												jLabel1)
																										.addGap(
																												18,
																												18,
																												18)
																										.addComponent(
																												emailTxt,
																												javax.swing.GroupLayout.DEFAULT_SIZE,
																												201,
																												Short.MAX_VALUE))
																						.addGroup(
																								jPanel2Layout
																										.createSequentialGroup()
																										.addComponent(
																												jLabel4)
																										.addGap(
																												18,
																												18,
																												18)
																										.addComponent(
																												adTxt,
																												javax.swing.GroupLayout.DEFAULT_SIZE,
																												201,
																												Short.MAX_VALUE))
																						.addGroup(
																								jPanel2Layout
																										.createSequentialGroup()
																										.addComponent(
																												jLabel8)
																										.addGap(
																												18,
																												18,
																												18)
																										.addComponent(
																												adUrlTxt,
																												javax.swing.GroupLayout.PREFERRED_SIZE,
																												136,
																												javax.swing.GroupLayout.PREFERRED_SIZE)
																										.addPreferredGap(
																												javax.swing.LayoutStyle.ComponentPlacement.RELATED,
																												8,
																												Short.MAX_VALUE)
																										.addComponent(
																												jButton1)
																										.addPreferredGap(
																												javax.swing.LayoutStyle.ComponentPlacement.RELATED))
																						.addComponent(
																								UpdateBtn,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								225,
																								javax.swing.GroupLayout.PREFERRED_SIZE))))
										.addGap(53, 53, 53)));
		jPanel2Layout
				.setVerticalGroup(jPanel2Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel2Layout
										.createSequentialGroup()
										.addGap(39, 39, 39)
										.addComponent(jLabel3)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addComponent(
												jLabel2,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												33,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addGroup(
												jPanel2Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(
																jLabel5,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																23,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(
																unameTxt,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGap(8, 8, 8)
										.addGroup(
												jPanel2Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING,
																false)
														.addGroup(
																jPanel2Layout
																		.createSequentialGroup()
																		.addComponent(
																				companyTxt,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addComponent(
																				phoneTxt,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				javax.swing.GroupLayout.PREFERRED_SIZE))
														.addGroup(
																jPanel2Layout
																		.createSequentialGroup()
																		.addComponent(
																				jLabel6)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				Short.MAX_VALUE)
																		.addComponent(
																				jLabel7)))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(
												jPanel2Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(
																emailTxt,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(jLabel1))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(
												jPanel2Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(jLabel4)
														.addComponent(
																adTxt,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(
												jPanel2Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.TRAILING)
														.addComponent(jLabel8)
														.addGroup(
																jPanel2Layout
																		.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.BASELINE)
																		.addComponent(
																				adUrlTxt,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addComponent(
																				jButton1)))
										.addGap(29, 29, 29)
										.addComponent(
												UpdateBtn,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												38,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(57, 57, 57)));

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jPanel2, javax.swing.GroupLayout.Alignment.TRAILING,
				javax.swing.GroupLayout.DEFAULT_SIZE,
				javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
		layout.setVerticalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				layout.createSequentialGroup().addComponent(jPanel2,
						javax.swing.GroupLayout.DEFAULT_SIZE, 411,
						Short.MAX_VALUE).addGap(143, 143, 143)));

		pack();
	}// </editor-fold>
	//GEN-END:initComponents

	private void UpdateBtnActionPerformed(java.awt.event.ActionEvent evt) {
		String uname = unameTxt.getText();
		String cTxt = companyTxt.getText();
		String phone = phoneTxt.getText();
		String email = emailTxt.getText();
		String adname = adTxt.getText();
		String adUrl = adUrlTxt.getText();
		
		
	
		if(uname.equals("")||cTxt.equals("")||phone.equals("")||email.equals("")||adname.equals("")||adUrl.equals("")){
			JOptionPane.showMessageDialog(this, "请输入完整信息");
		}else{
			if(ModelFactory.UserNameFormat(uname)){
				JOptionPane.showMessageDialog(this, "请输入真实姓名");
			}else if(!ModelFactory.PhoneFormat(phone)){
				JOptionPane.showMessageDialog(this, "请输入正确的电话号码");
			}else if(!ModelFactory.emailFormat(email)){
				JOptionPane.showMessageDialog(this, "请输入正确的邮箱");
			}else{
				try {
					Admin.insertAd(uname, cTxt, phone, email,adname,adUrl );
					JOptionPane.showMessageDialog(this, "添加成功");
					String adUrlString = adUrl.replaceAll("\\\\", "//");
					String imgUrl = adUrlString.substring(adUrlString.lastIndexOf("/")+1);
					Ad.setImgUrl(imgUrl);
					ModelFactory.copyFile(adUrl, "src/imgs/"+imgUrl);
					
					/*数据更新*/
					this.datas = Ad.Adconvery("");
					this.atm.setRowValues(this.datas);
					this.jsl.invalidate();
					
					this.dispose();
				} catch (SQLException e) {
					JOptionPane.showMessageDialog(this, "添加失败");
				
					e.printStackTrace();
				}
			}

			
		}
		

	}
	/***
	 * 选择图片按钮
	 * @param evt
	 */
	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
		
		JFileChooser jfc = new JFileChooser();
		int value = jfc.showDialog(new JLabel(), "选择");
		if(value==JFileChooser.APPROVE_OPTION){
			String path = jfc.getSelectedFile().getAbsolutePath();
			adUrlTxt.setText(path);
			
		}

	}
	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				try {
					org.jb2011.lnf.beautyeye.BeautyEyeLNFHelper
							.launchBeautyEyeLNF();
				} catch (Exception e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
				ModelFactory.InitGlobalFont(new Font("微软雅黑",
						Font.CENTER_BASELINE, 12));
				new AddAd().setVisible(true);

			}
		});
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JButton UpdateBtn;
	private javax.swing.JTextField adTxt;
	private javax.swing.JTextField adUrlTxt;
	private javax.swing.JTextField emailTxt;
	private javax.swing.JButton jButton1;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JLabel jLabel7;
	private javax.swing.JLabel jLabel8;
	private javax.swing.JPanel jPanel2;
	private javax.swing.JTextField companyTxt;
	private javax.swing.JTextField phoneTxt;
	private javax.swing.JTextField unameTxt;
	// End of variables declaration//GEN-END:variables

}