/*
 * AddUser.java
 *
 * Created on __DATE__, __TIME__
 */

package View;

import java.awt.Image;
import java.awt.Toolkit;
import java.sql.SQLException;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

import Control.User;

/**
 *
 * @author  __USER__
 */
public class AddUser extends javax.swing.JFrame {

	/** Creates new form AddUser */
	public AddUser() {
		initComponents();
		Image icon = Toolkit.getDefaultToolkit().getImage("imgs//icon.jpg");
		this.setTitle("添加新用户");
		this.setVisible(true);
		this.setResizable(false);
		this.setLocationRelativeTo(null);
		this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
		this.setIconImage(icon);
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jPanel1 = new javax.swing.JPanel();
		jLabel2 = new javax.swing.JLabel();
		uidTxt = new javax.swing.JTextField();
		jLabel4 = new javax.swing.JLabel();
		jLabel5 = new javax.swing.JLabel();
		unameTxt = new javax.swing.JTextField();
		upassTxt = new javax.swing.JPasswordField();
		jLabel6 = new javax.swing.JLabel();
		jLabel7 = new javax.swing.JLabel();
		phoneTxt = new javax.swing.JTextField();
		emailTxt = new javax.swing.JTextField();
		jLabel1 = new javax.swing.JLabel();
		registerBtn = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		jLabel2.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18));
		jLabel2
				.setText("\u8f93\u5165\u7528\u6237\u8d44\u6599\u7528\u4ee5\u6dfb\u52a0\u65b0\u7528\u6237");

		uidTxt.setForeground(new java.awt.Color(153, 153, 153));
		uidTxt.setText("\u8bf7\u8f93\u5165\u7528\u6237ID");

		jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource(
				"/imgs/id.png"))); // NOI18N

		jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource(
				"/imgs/user-icon.png"))); // NOI18N

		unameTxt.setForeground(new java.awt.Color(153, 153, 153));
		unameTxt.setText("\u8f93\u5165\u7528\u6237\u540d");

		upassTxt.setForeground(new java.awt.Color(153, 153, 153));
		upassTxt.setText("qing sdads");

		jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource(
				"/imgs/pass-icon.png"))); // NOI18N

		jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource(
				"/imgs/tel-icon.png"))); // NOI18N

		phoneTxt.setForeground(new java.awt.Color(153, 153, 153));
		phoneTxt.setText("\u8bf7\u8f93\u5165\u7535\u8bdd\u53f7\u7801");
		phoneTxt.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				phoneTxtActionPerformed(evt);
			}
		});

		emailTxt.setForeground(new java.awt.Color(153, 153, 153));
		emailTxt.setText("\u8bf7\u8f93\u5165\u90ae\u7bb1\u5730\u5740");

		jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource(
				"/imgs/mail-icon.png"))); // NOI18N

		registerBtn.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 24));
		registerBtn.setText("\u6dfb\u52a0\u7528\u6237");
		registerBtn.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				registerBtnActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(
				jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout
				.setHorizontalGroup(jPanel1Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								javax.swing.GroupLayout.Alignment.TRAILING,
								jPanel1Layout
										.createSequentialGroup()
										.addContainerGap(68, Short.MAX_VALUE)
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																jPanel1Layout
																		.createSequentialGroup()
																		.addGroup(
																				jPanel1Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.TRAILING)
																						.addComponent(
																								jLabel6)
																						.addComponent(
																								jLabel7)
																						.addComponent(
																								jLabel1)
																						.addComponent(
																								jLabel4)
																						.addComponent(
																								jLabel5))
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addGroup(
																				jPanel1Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING,
																								false)
																						.addComponent(
																								upassTxt)
																						.addComponent(
																								emailTxt)
																						.addComponent(
																								phoneTxt)
																						.addComponent(
																								unameTxt)
																						.addComponent(
																								uidTxt,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								220,
																								javax.swing.GroupLayout.PREFERRED_SIZE)))
														.addComponent(
																jLabel2,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																276,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addGroup(
																jPanel1Layout
																		.createSequentialGroup()
																		.addGap(
																				10,
																				10,
																				10)
																		.addComponent(
																				registerBtn,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				225,
																				javax.swing.GroupLayout.PREFERRED_SIZE)))
										.addGap(55, 55, 55)));
		jPanel1Layout
				.setVerticalGroup(jPanel1Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								javax.swing.GroupLayout.Alignment.TRAILING,
								jPanel1Layout
										.createSequentialGroup()
										.addGap(43, 43, 43)
										.addComponent(
												jLabel2,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												33,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(29, 29, 29)
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(jLabel4)
														.addComponent(
																uidTxt,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(
																jLabel5,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																23,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(
																unameTxt,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGap(11, 11, 11)
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.TRAILING)
														.addComponent(
																upassTxt,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																25,
																Short.MAX_VALUE)
														.addComponent(jLabel6))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.TRAILING)
														.addComponent(jLabel7)
														.addComponent(
																phoneTxt,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.TRAILING)
														.addComponent(jLabel1)
														.addComponent(
																emailTxt,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGap(39, 39, 39)
										.addComponent(
												registerBtn,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												38,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(24, 24, 24)));

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE,
				javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
		layout.setVerticalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE,
				javax.swing.GroupLayout.DEFAULT_SIZE,
				javax.swing.GroupLayout.PREFERRED_SIZE));

		pack();
	}// </editor-fold>
	//GEN-END:initComponents

	private void phoneTxtActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	private void registerBtnActionPerformed(java.awt.event.ActionEvent evt) {
		String userid = uidTxt.getText();
		String userName = unameTxt.getText();
		String userPass = new String(this.upassTxt.getPassword());
		String userphone = phoneTxt.getText();
		String useremail = emailTxt.getText();
		if (userid.equals("") || userName.equals("") || userPass.equals("")
				|| userphone.equals("") || useremail.equals((""))) {
			JOptionPane.showMessageDialog(this, "请填写完整信息");
		} else {
			try {
				String result = User.uRegister(userid, userName, userPass,
						userphone, useremail);
				JOptionPane.showMessageDialog(this, result);
				if (result.equals("添加成功")) {
					new Login();
				}
			} catch (SQLException e) {
				e.printStackTrace();
			}
		}
	}

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new AddUser().setVisible(true);
			}
		});
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JTextField emailTxt;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JLabel jLabel7;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JTextField phoneTxt;
	private javax.swing.JButton registerBtn;
	private javax.swing.JTextField uidTxt;
	private javax.swing.JTextField unameTxt;
	private javax.swing.JPasswordField upassTxt;
	// End of variables declaration//GEN-END:variables

}