/*
 * UserRegister.java
 *
 * Created on __DATE__, __TIME__
 */

package View;

import java.awt.Font;
import java.awt.Image;
import java.awt.Toolkit;
import java.sql.SQLException;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

import Control.FontControl;
import Control.ModelFactory;
import Control.User;

/**
 * 
 * @author __USER__
 */
public class UserUpdate extends javax.swing.JFrame {

	private static final long serialVersionUID = 1L;

	/** Creates new form UserRegister */
	public UserUpdate() {
		initComponents();
		Image icon = Toolkit.getDefaultToolkit().getImage("imgs//icon.jpg");
		this.setTitle("用户注册");
		this.setVisible(true);
		this.setResizable(false);
		this.setLocationRelativeTo(null);
		this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
		this.setIconImage(icon);

	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jPanel2 = new javax.swing.JPanel();
		jLabel5 = new javax.swing.JLabel();
		jLabel6 = new javax.swing.JLabel();
		jLabel7 = new javax.swing.JLabel();
		phoneTxt = new javax.swing.JTextField();
		UpdateBtn = new javax.swing.JButton();
		emailTxt = new javax.swing.JTextField();
		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		jLabel3 = new javax.swing.JLabel();
		unameTxt = new javax.swing.JTextField();
		passwordTxt = new javax.swing.JTextField();
		jLabel4 = new javax.swing.JLabel();
		jLabel8 = new javax.swing.JLabel();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource(
				"/imgs/user-icon.png"))); // NOI18N

		jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource(
				"/imgs/pass-icon.png"))); // NOI18N

		jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource(
				"/imgs/tel-icon.png"))); // NOI18N

		phoneTxt.setForeground(new java.awt.Color(153, 153, 153));
		phoneTxt
				.setText(User.getPhone());

		UpdateBtn.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 24));
		UpdateBtn.setText("\u4fee\u6539\u8d44\u6599");
		UpdateBtn.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				UpdateBtnActionPerformed(evt);
			}
		});

		emailTxt.setForeground(new java.awt.Color(153, 153, 153));
		emailTxt
				.setText(User.getEmail());

		jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource(
				"/imgs/mail-icon.png"))); // NOI18N

		jLabel2.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18));
		jLabel2
				.setText("\u73b0\u5728\u53ef\u4ee5\u4fee\u6539\u4f60\u7684\u8d26\u53f7");

		jLabel3.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18));
		jLabel3.setText("\u6b22\u8fce\u4f7f\u7528SkyDisk");

		unameTxt.setForeground(new java.awt.Color(153, 153, 153));
		unameTxt.setText(User.getUsername());

		passwordTxt.setForeground(new java.awt.Color(153, 153, 153));
		passwordTxt.setText(User.getUserpassword());

		jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource(
				"/imgs/id.png"))); // NOI18N

		jLabel8.setText(User.getUserid());

		javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(
				jPanel2);
		jPanel2.setLayout(jPanel2Layout);
		jPanel2Layout
				.setHorizontalGroup(jPanel2Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								javax.swing.GroupLayout.Alignment.TRAILING,
								jPanel2Layout
										.createSequentialGroup()
										.addContainerGap(54, Short.MAX_VALUE)
										.addGroup(
												jPanel2Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.TRAILING)
														.addComponent(
																UpdateBtn,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																225,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(
																jLabel2,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																204,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(
																jLabel3,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																191,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGap(58, 58, 58))
						.addGroup(
								jPanel2Layout
										.createSequentialGroup()
										.addGap(65, 65, 65)
										.addGroup(
												jPanel2Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																jPanel2Layout
																		.createSequentialGroup()
																		.addComponent(
																				jLabel4)
																		.addGap(
																				18,
																				18,
																				18)
																		.addComponent(
																				jLabel8,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				163,
																				Short.MAX_VALUE))
														.addGroup(
																jPanel2Layout
																		.createSequentialGroup()
																		.addGroup(
																				jPanel2Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.TRAILING)
																						.addComponent(
																								jLabel7)
																						.addComponent(
																								jLabel5)
																						.addComponent(
																								jLabel6)
																						.addComponent(
																								jLabel1))
																		.addGap(
																				18,
																				18,
																				18)
																		.addGroup(
																				jPanel2Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING,
																								false)
																						.addComponent(
																								phoneTxt)
																						.addComponent(
																								passwordTxt)
																						.addComponent(
																								unameTxt)
																						.addComponent(
																								emailTxt,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								163,
																								Short.MAX_VALUE))))
										.addContainerGap(66, Short.MAX_VALUE)));
		jPanel2Layout
				.setVerticalGroup(jPanel2Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel2Layout
										.createSequentialGroup()
										.addGap(39, 39, 39)
										.addComponent(jLabel3)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addComponent(
												jLabel2,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												33,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(
												jPanel2Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.TRAILING,
																false)
														.addComponent(
																jLabel8,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																Short.MAX_VALUE)
														.addComponent(
																jLabel4,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																Short.MAX_VALUE))
										.addGap(12, 12, 12)
										.addGroup(
												jPanel2Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																javax.swing.GroupLayout.Alignment.TRAILING,
																jPanel2Layout
																		.createSequentialGroup()
																		.addComponent(
																				jLabel5,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				23,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED))
														.addGroup(
																jPanel2Layout
																		.createSequentialGroup()
																		.addComponent(
																				unameTxt,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
										.addGroup(
												jPanel2Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(jLabel6)
														.addComponent(
																passwordTxt,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(
												jPanel2Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(jLabel7)
														.addComponent(
																phoneTxt,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(
												jPanel2Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.TRAILING)
														.addComponent(jLabel1)
														.addComponent(
																emailTxt,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGap(27, 27, 27)
										.addComponent(
												UpdateBtn,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												38,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(61, 61, 61)));

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				layout.createSequentialGroup().addComponent(jPanel2,
						javax.swing.GroupLayout.DEFAULT_SIZE,
						javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addContainerGap()));
		layout.setVerticalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 403,
				Short.MAX_VALUE));

		pack();
	}// </editor-fold>
	//GEN-END:initComponents

	private void UpdateBtnActionPerformed(java.awt.event.ActionEvent evt) {
		String uname = unameTxt.getText();
		String upass = passwordTxt.getText();
		String phone = phoneTxt.getText();
		String email = emailTxt.getText();
		try {
			User.updateUserMessage(uname, upass, phone, email, User.getUserid());
			JOptionPane.showMessageDialog(this, "修改成功");
			this.dispose();
		} catch (SQLException e) {
			JOptionPane.showMessageDialog(this, "修改失败");
			e.printStackTrace();
		}

	}

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				try {
					org.jb2011.lnf.beautyeye.BeautyEyeLNFHelper
							.launchBeautyEyeLNF();
				} catch (Exception e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
				ModelFactory.InitGlobalFont(new Font("微软雅黑",
						Font.CENTER_BASELINE, 12));
				new UserUpdate().setVisible(true);

			}
		});
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JButton UpdateBtn;
	private javax.swing.JTextField emailTxt;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JLabel jLabel7;
	private javax.swing.JLabel jLabel8;
	private javax.swing.JPanel jPanel2;
	private javax.swing.JTextField passwordTxt;
	private javax.swing.JTextField phoneTxt;
	private javax.swing.JTextField unameTxt;
	// End of variables declaration//GEN-END:variables

}